plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.115'
    id 'org.jetbrains.kotlin.jvm'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

// Mojang ships Java 17 to end users in 1.18+, so your mod should target Java 17.
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    // Specify the version of MinecraftForge to use.
    version = project.minecraft_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // This line is optional. Access Transformers are automatically detected
     accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            programArguments.addAll("--username", "wu1wu2")
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
//            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            //mixin
            systemProperty 'mixin.verbose', 'true'
            systemProperty 'mixin.export', 'true'
            systemProperty 'mixin.dumpTargetOnFailure', 'true'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        // define mod <-> source bindings
        // these are used to tell the game which sources are for which mod
        // mostly optional in a single mod project
        // but multi mod projects should define one per mod
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    maven { url 'https://maven.blamejared.com' }
     flatDir {
         dir 'libs'
     }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    mavenCentral()
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "mixins.${mod_id}.json"
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

jar {
    manifest.attributes([
            "MixinConfigs": "mixins.${mod_id}.json"
    ])
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs += [
            // 配置注解处理器输出的 refmap 文件路径
            "-AoutRefMapFile=${buildDir}/resources/main/${mod_id}.refmap.json",
    ]
}

//mixin {
//    // Refmaps for each SourceSet
//    add sourceSets.main, "${mod_id}.refmap.json"
//
//    // Configs to add to runs and jars
//    config "mixins.${mod_id}.json"
//
//    // Specify options for dev run configs
//    debug.verbose = true
//    debug.export = true
//    dumpTargetOnFailure = true
//
//    // Options for the Annotation Processor
//    quiet
//}

//dependencies {
//
//    //依赖
//    implementation  fg.deobf("blank:FarmersDelight-1.20.1:1.2.9")
//    implementation  fg.deobf("blank:goety:2.5.36.1")
//    //runtimeOnly  fg.deobf("blank:Goety-Revelation:2.2.7-forge-1.20.1")
//
//
//    //优化
//    modRuntimeOnly fg.deobf("blank:dynamic-fps:3.9.5+minecraft-1.20.0-forge")
//    runtimeOnly fg.deobf("blank:embeddium:0.3.31+mc1.20.1")
//    runtimeOnly fg.deobf("blank:oculus:mc1.20.1-1.8.0")
//    runtimeOnly fg.deobf("blank:kotlinforforge:4.11.0-all")
//    runtimeOnly fg.deobf("blank:radium:mc1.20.1-0.12.4+git.26c9d8e")
//    //runtimeOnly fg.deobf("blank:BadOptimizations:2.3.0-1.20.1")
//    runtimeOnly fg.deobf("blank:cloth-config:11.1.136-forge")
//    runtimeOnly fg.deobf("blank:fzzy_config:0.7.1+1.20.1+forge")
//
//    runtimeOnly fg.deobf("blank:ModernUI-Forge:1.20.1-3.11.1.6-universal")
//
//
//
//
//    runtimeOnly fg.deobf("blank:rubidium:extra-0.5.4.4+mc1.20.1-build.131")
//    runtimeOnly fg.deobf("blank:saturn:mc1.20.1-0.1.3")
//
//    runtimeOnly fg.deobf("blank:sodiumextras:forge-1.0.7-1.20.1")
//    runtimeOnly fg.deobf("blank:starlight:1.1.2+forge.1cda73c")
//    runtimeOnly fg.deobf("blank:CullLessLeaves:Reforged-1.20.1-1.0.5")
//
//
//    runtimeOnly fg.deobf("blank:flerovium-forge:1.20.1-1.2.14-all")
//    //runtimeOnly fg.deobf("blank:modernfix-forge:5.24.3+mc1.20.1")
//    runtimeOnly fg.deobf("blank:noisium-forge:2.3.0+mc1.20-1.20.1")
//    runtimeOnly fg.deobf("blank:particle_core:0.2.6+1.20.1+forge")
//    runtimeOnly fg.deobf("blank:RuOK:1.7.1_1.20.1-Forge")
//    runtimeOnly fg.deobf("blank:sodiumoptionsapi:forge-1.0.10-1.20.1")
//    runtimeOnly fg.deobf("blank:invalidsidelogger:1.0.0")
//
//
//
//
//
////会崩溃
////    runtimeOnly fg.deobf("blank:ImmediatelyFast:Forge-1.5.1+1.20.4")
////    runtimeOnly fg.deobf("blank:entityculling:forge-1.8.2-mc1.20.1")
//
//
//    //辅助
//    runtimeOnly fg.deobf("blank:XaerosWorldMap-Forge1.20:1.39.12")
//    runtimeOnly fg.deobf("blank:worldedit-mod:7.2.15")
//    runtimeOnly fg.deobf("blank:ftb-ultimine-forge:2001.1.6")
//    runtimeOnly fg.deobf("blank:ftb-library-forge:2001.2.10")
//    runtimeOnly fg.deobf("blank:architectury:9.2.14-forge")
//    runtimeOnly fg.deobf("blank:jei:1.20.1-forge-15.20.0.113")
//    runtimeOnly fg.deobf("blank:jecharacters:1.20.1-forge-4.5.16")
//
//
//
//
////双端mod
//
//    runtimeOnly  fg.deobf("blank:appleskin-forge-mc1.20.1:2.5.1")
//    runtimeOnly  fg.deobf("blank:create-1.20.1:6.0.6")
//
//
//
//
//
//    runtimeOnly  fg.deobf("blank:dummmmmmy-1.20:2.0.6")
//    runtimeOnly  fg.deobf("blank:moonlight-1.20:2.14.1-forge")
////
//    runtimeOnly  fg.deobf("blank:AttributeFix-Forge-1.20.1:21.0.4")
////
//    runtimeOnly  fg.deobf("blank:CustomSkinLoader_ForgeV2:14.23")
////    runtimeOnly  fg.deobf("blank:CustomSkinLoader:14.23")
//
////    runtimeOnly  fg.deobf("blank:twilightforest-1.20.1:4.3.2508-universal")
//
//    runtimeOnly  fg.deobf("blank:badpackets-forge:0.4.3")
//    runtimeOnly  fg.deobf("blank:wthit-forge:8.15.3")
//
//    runtimeOnly  fg.deobf("blank:lanserverproperties:1.11.1-forge")
//    runtimeOnly  fg.deobf("blank:IAS-Forge-1.20.1:9.0.2")
//
//    runtimeOnly  fg.deobf("blank:L_Enders_Cataclysm:2.58-1.20.1")
//    runtimeOnly  fg.deobf("blank:citadel:2.6.1-1.20.1")
//    runtimeOnly  fg.deobf("blank:lionfishapi:2.4")
//
//    runtimeOnly  fg.deobf("blank:curios-forge:5.14.1+1.20.1")
//
//    runtimeOnly  fg.deobf("blank:mobbattle-1.20.1:2.4.13-forge")
//
//
//    runtimeOnly  fg.deobf("blank:DungeonsArise-1.20.1:2.1.58")
////    runtimeOnly  fg.deobf("blank:lostcities-1.20:7.4.1")
//
//    runtimeOnly  fg.deobf("blank:spark:1.10.53-forge")
//
//
//    // Example mod dependency using a mod jar from ./libs with a flat dir repository
//    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
//    // The group id is ignored when searching -- in this case, it is "blank"
//    // implementation fg.deobf("blank:coolmod-${mc_version}:${coolmod_version}")
//
//    // For more info:
//    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
//    // http://www.gradle.org/docs/current/userguide/dependency_management.html
//
//}

dependencies {
    modImplementation "curse.maven:farmers-delight-398521:8007609"//1.3.1
//    modImplementation "curse.maven:goety-586095:7966952"// 2.5.52.4
    modImplementation "curse.maven:goety-586095:8242254"//2.5.54.5

//    modImplementation "curse.maven:goety-revelation-1236817:6892481"

     compileOnly "blank:[Forge]RevelationFix-1.20.1-4.0"
    modImplementation "curse.maven:curios-309927:6418456"//5.14.1

    //帕秋莉
    modCompileOnly "vazkii.patchouli:Patchouli:1.20.1-84.1-FORGE:api"
    modImplementation "blank:Patchouli-1.20.1-84.1-FORGE"//2.5.36.1

    //jei
    compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mc_version}-forge-api:${jei_version}"
    // at runtime, use the full JEI jar for Forge
    modRuntimeOnly "mezz.jei:jei-${mc_version}-forge:${jei_version}"
    modRuntimeOnly "blank:appleskin-forge-mc1.20.1-2.5.1"
    modRuntimeOnly "blank:L_Enders_Cataclysm-2.58-1.20.1"
    modRuntimeOnly "blank:lionfishapi-2.4"
    modRuntimeOnly "blank:mobbattle-1.20.1-2.4.13-forge"
    modRuntimeOnly "blank:XaerosWorldMap-Forge1.20-1.39.12"
    modRuntimeOnly  "blank:dummmmmmy-1.20:2.0.6"
    modRuntimeOnly  "blank:moonlight-1.20:2.14.1-forge"
    modCompileOnly  "blank:Jade-1.20.1-Forge-11.13.1"
    modRuntimeOnly  "blank:Jade-1.20.1-Forge-11.13.1"
    modRuntimeOnly  "blank:l2library-2.5.3"

    //nbt编辑器
    modRuntimeOnly  "curse.maven:ibe-editor-256822:4994072"
    //性能检测spark
    modRuntimeOnly  "curse.maven:spark-361579:4738952"
    modRuntimeOnly  "curse.maven:enchantment-descriptions-250419:7336071"
    modRuntimeOnly  "curse.maven:bookshelf-228525:5423987"
    //摩登ui
    modRuntimeOnly "curse.maven:modern-ui-352491:6956345"
    //光影
    modRuntimeOnly "curse.maven:oculus-581495:6020952"
    modRuntimeOnly "curse.maven:xenon-564239:5752040"
}


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version        : minecraft_version,
            minecraft_version_range  : minecraft_version_range,
            forge_version            : forge_version,
            forge_version_range      : forge_version_range,
            loader_version_range     : loader_version_range,
            mod_id                   : mod_id,
            mod_name                 : mod_name,
            mod_license              : mod_license,
            mod_version              : mod_version,
            mod_authors              : mod_authors,
            mod_description          : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
legacyForge.ideSyncTask generateModMetadata


// Example configuration to allow publishing using the maven-publish plugin
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
kotlin {
    jvmToolchain(17)
}
